
-- Migration: Populate Relocators Data from Markdown
-- Generated by script


-- Update Agoodday Relocation & Real Estate
UPDATE relocators 
SET 
    contact_email = 'info@agoodday.ch',
    phone_number = '+41 22 366 97 77',
    website = 'https://www.agoodday.ch/',
    founded_year = 2017,
    employee_count = 'Not specified',
    address_street = 'Agoodday Relocation & Real Estate Office',
    address_city = 'La Côte',
    address_zip = '0000'
WHERE name ILIKE 'Agoodday Relocation & Real Estate';

-- Insert Office for Agoodday Relocation & Real Estate
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Agoodday Relocation & Real Estate Office', 'La Côte', '0000', true
FROM relocators 
WHERE name ILIKE 'Agoodday Relocation & Real Estate'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Alliance Relocation Switzerland
UPDATE relocators 
SET 
    contact_email = 'info@alliance-relocation.ch',
    phone_number = '+41 79 781 78 80',
    website = 'https://www.alliance-relocation.ch/',
    founded_year = 2024,
    employee_count = '5 partners',
    address_street = 'Im Eichli 21',
    address_city = 'Oberägeri',
    address_zip = '6315'
WHERE name ILIKE 'Alliance Relocation Switzerland';

-- Insert Office for Alliance Relocation Switzerland
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Im Eichli 21', 'Oberägeri', '6315', true
FROM relocators 
WHERE name ILIKE 'Alliance Relocation Switzerland'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update AM Relocation
UPDATE relocators 
SET 
    contact_email = 'info@amrelocation.ch',
    phone_number = NULL,
    website = 'https://am-relocation.ch/',
    founded_year = NULL,
    employee_count = 'Not specified',
    address_street = 'AM Relocation Office',
    address_city = 'Zurich',
    address_zip = '0000'
WHERE name ILIKE 'AM Relocation';

-- Insert Office for AM Relocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'AM Relocation Office', 'Zurich', '0000', true
FROM relocators 
WHERE name ILIKE 'AM Relocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Anchor Relocation
UPDATE relocators 
SET 
    contact_email = 'info@anchor-relocation.ch',
    phone_number = '+41 44 383 23 23',
    website = 'https://anchor-relocation.ch/',
    founded_year = NULL,
    employee_count = '6+',
    address_street = 'Rämistrasse 8',
    address_city = 'Zürich',
    address_zip = '8001'
WHERE name ILIKE 'Anchor Relocation';

-- Insert Office for Anchor Relocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Rämistrasse 8', 'Zürich', '8001', true
FROM relocators 
WHERE name ILIKE 'Anchor Relocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Auris Relocation
UPDATE relocators 
SET 
    contact_email = 'info@aurisrelocation.com',
    phone_number = '+41 44 808 60 00',
    website = 'https://www.aurisrelocation.com/',
    founded_year = 2010,
    employee_count = 'Not specified',
    address_street = 'Sternenstrasse 12',
    address_city = 'Zurich',
    address_zip = '8002'
WHERE name ILIKE 'Auris Relocation';

-- Insert Office for Auris Relocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Sternenstrasse 12', 'Zurich', '8002', true
FROM relocators 
WHERE name ILIKE 'Auris Relocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Bridging Cultures Relocation
UPDATE relocators 
SET 
    contact_email = 'info@bridgingculturesrelocation.com',
    phone_number = '+41 79 226 96 41',
    website = 'https://www.bridgingculturesrelocation.com/',
    founded_year = 1997,
    employee_count = 'Not specified',
    address_street = 'Zugerstrasse 8a',
    address_city = 'Baar',
    address_zip = '6340'
WHERE name ILIKE 'Bridging Cultures Relocation';

-- Insert Office for Bridging Cultures Relocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Zugerstrasse 8a', 'Baar', '6340', true
FROM relocators 
WHERE name ILIKE 'Bridging Cultures Relocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update CONTENTUM Relocation Basel
UPDATE relocators 
SET 
    contact_email = 'martina@contentum-relocation.com',
    phone_number = '+41 76 502 21 22',
    website = 'https://www.contentum-relocation.com/',
    founded_year = 2015,
    employee_count = '4',
    address_street = 'Ahornstrasse 27',
    address_city = 'Basel',
    address_zip = '4055'
WHERE name ILIKE 'CONTENTUM Relocation Basel';

-- Insert Office for CONTENTUM Relocation Basel
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Ahornstrasse 27', 'Basel', '4055', true
FROM relocators 
WHERE name ILIKE 'CONTENTUM Relocation Basel'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Crown Relocations Switzerland
UPDATE relocators 
SET 
    contact_email = 'switzerland@crownrelo.com',
    phone_number = '+41 22 518 88 70',
    website = 'http://www.crownrelo.com/intl/en-ch/',
    founded_year = 1965,
    employee_count = 'Not specified',
    address_street = 'Industriestrasse 44',
    address_city = 'Wallisellen',
    address_zip = '8304'
WHERE name ILIKE 'Crown Relocations Switzerland';

-- Insert Office for Crown Relocations Switzerland
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Industriestrasse 44', 'Wallisellen', '8304', true
FROM relocators 
WHERE name ILIKE 'Crown Relocations Switzerland'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update EasyRelocation
UPDATE relocators 
SET 
    contact_email = 'info@easy-relocation.ch',
    phone_number = '+41 77 535 26 83',
    website = 'https://www.easy-relocation.ch/',
    founded_year = 2008,
    employee_count = 'Not specified',
    address_street = 'EasyRelocation Office',
    address_city = 'Zug',
    address_zip = '0000'
WHERE name ILIKE 'EasyRelocation';

-- Insert Office for EasyRelocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'EasyRelocation Office', 'Zug', '0000', true
FROM relocators 
WHERE name ILIKE 'EasyRelocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Executive Relocation
UPDATE relocators 
SET 
    contact_email = 'welcome@executive-relocation.ch',
    phone_number = '+41 76 346 51 17',
    website = 'https://www.executive-relocation.ch/',
    founded_year = 2012,
    employee_count = 'Not specified',
    address_street = 'Etzlibergstrasse 19',
    address_city = 'Thalwil',
    address_zip = '8800'
WHERE name ILIKE 'Executive Relocation';

-- Insert Office for Executive Relocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Etzlibergstrasse 19', 'Thalwil', '8800', true
FROM relocators 
WHERE name ILIKE 'Executive Relocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Expat Savvy
UPDATE relocators 
SET 
    contact_email = 'contact@expat-savvy.ch',
    phone_number = '+41 79 123 45 67',
    website = 'https://expat-savvy.ch/',
    founded_year = 2024,
    employee_count = '4',
    address_street = 'Zurich',
    address_city = 'Zurich',
    address_zip = '8000'
WHERE name ILIKE 'Expat Savvy';

-- Insert Office for Expat Savvy
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Zurich', 'Zurich', '8000', true
FROM relocators 
WHERE name ILIKE 'Expat Savvy'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Expat Services Switzerland
UPDATE relocators 
SET 
    contact_email = 'welcome@expatservices.ch',
    phone_number = '+41 44 552 72 31',
    website = 'https://www.expatservices.ch/',
    founded_year = 2020,
    employee_count = 'Not specified',
    address_street = 'Lavaterstrasse 67',
    address_city = 'Zürich',
    address_zip = '8002'
WHERE name ILIKE 'Expat Services Switzerland';

-- Insert Office for Expat Services Switzerland
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Lavaterstrasse 67', 'Zürich', '8002', true
FROM relocators 
WHERE name ILIKE 'Expat Services Switzerland'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update H.O.M.E.S Basel
UPDATE relocators 
SET 
    contact_email = 'info@homesbasel.com',
    phone_number = '+41 79 454 13 09',
    website = 'https://relocation-basel.ch/',
    founded_year = NULL,
    employee_count = 'Not specified',
    address_street = 'Spechtweg 7',
    address_city = 'Riehen',
    address_zip = '4125'
WHERE name ILIKE 'H.O.M.E.S Basel';

-- Insert Office for H.O.M.E.S Basel
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Spechtweg 7', 'Riehen', '4125', true
FROM relocators 
WHERE name ILIKE 'H.O.M.E.S Basel'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Include Relocation
UPDATE relocators 
SET 
    contact_email = 'info@includerelocation.ch',
    phone_number = NULL,
    website = 'https://www.zweers-include.com/',
    founded_year = 2023,
    employee_count = 'Not specified',
    address_street = 'Include Relocation Office',
    address_city = 'Basel',
    address_zip = '0000'
WHERE name ILIKE 'Include Relocation';

-- Insert Office for Include Relocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Include Relocation Office', 'Basel', '0000', true
FROM relocators 
WHERE name ILIKE 'Include Relocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Keller Swiss Group
UPDATE relocators 
SET 
    contact_email = 'basel@kellerswissgroup.com',
    phone_number = '+41 58 317 10 00',
    website = 'https://www.kellerswissgroup.com/',
    founded_year = 1990,
    employee_count = 'Not specified',
    address_street = 'Reinacherstrasse 121',
    address_city = 'Basel',
    address_zip = '4053'
WHERE name ILIKE 'Keller Swiss Group';

-- Insert Office for Keller Swiss Group
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Reinacherstrasse 121', 'Basel', '4053', true
FROM relocators 
WHERE name ILIKE 'Keller Swiss Group'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update La Boutique Relocation Switzerland
UPDATE relocators 
SET 
    contact_email = 'contact@laboutiquerelocation.ch',
    phone_number = '+41 76 567 68 65',
    website = 'https://www.laboutiquerelocation.ch/',
    founded_year = 2020,
    employee_count = 'Not specified',
    address_street = 'Avenue de Rhodanie 54',
    address_city = 'Lausanne',
    address_zip = '1007'
WHERE name ILIKE 'La Boutique Relocation Switzerland';

-- Insert Office for La Boutique Relocation Switzerland
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Avenue de Rhodanie 54', 'Lausanne', '1007', true
FROM relocators 
WHERE name ILIKE 'La Boutique Relocation Switzerland'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update La Relocation Group
UPDATE relocators 
SET 
    contact_email = 'info@larelocationgroup.ch',
    phone_number = NULL,
    website = 'https://larelocationgroup.com/',
    founded_year = 2024,
    employee_count = 'Not specified',
    address_street = 'La Relocation Group Office',
    address_city = 'Melide',
    address_zip = '0000'
WHERE name ILIKE 'La Relocation Group';

-- Insert Office for La Relocation Group
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'La Relocation Group Office', 'Melide', '0000', true
FROM relocators 
WHERE name ILIKE 'La Relocation Group'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Lifestylemanagers
UPDATE relocators 
SET 
    contact_email = 'welcome@lifestylemanagers.ch',
    phone_number = '+41 41 763 36 66',
    website = 'https://www.lifestylemanagers.ch/',
    founded_year = 2000,
    employee_count = '4',
    address_street = 'Sumpfstrasse 32',
    address_city = 'Steinhausen',
    address_zip = '6312'
WHERE name ILIKE 'Lifestylemanagers';

-- Insert Office for Lifestylemanagers
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Sumpfstrasse 32', 'Steinhausen', '6312', true
FROM relocators 
WHERE name ILIKE 'Lifestylemanagers'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Lodge Relocation
UPDATE relocators 
SET 
    contact_email = 'info@lodge-relocation.com',
    phone_number = '+41 22 700 11 88',
    website = 'https://www.lodge-relocation.com',
    founded_year = 1994,
    employee_count = '13',
    address_street = 'Lodge Relocation Office',
    address_city = 'Geneva',
    address_zip = '0000'
WHERE name ILIKE 'Lodge Relocation';

-- Insert Office for Lodge Relocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Lodge Relocation Office', 'Geneva', '0000', true
FROM relocators 
WHERE name ILIKE 'Lodge Relocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Lugano Relocation Service
UPDATE relocators 
SET 
    contact_email = 'info@luganorelocationservice.ch',
    phone_number = '+41 79 420 77 43',
    website = 'https://www.luganorelocationservice.ch/',
    founded_year = 2007,
    employee_count = 'Not specified',
    address_street = 'Casella Postale 624',
    address_city = 'Lugano',
    address_zip = '6906'
WHERE name ILIKE 'Lugano Relocation Service';

-- Insert Office for Lugano Relocation Service
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Casella Postale 624', 'Lugano', '6906', true
FROM relocators 
WHERE name ILIKE 'Lugano Relocation Service'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Matterhorn Relocation
UPDATE relocators 
SET 
    contact_email = 'mail@matterhorn-relocation.com',
    phone_number = '+41 75 500 08 08',
    website = 'https://www.matterhorn-relocation.com/',
    founded_year = 2012,
    employee_count = '6',
    address_street = 'Seestrasse 1',
    address_city = 'Rüschlikon',
    address_zip = '8803'
WHERE name ILIKE 'Matterhorn Relocation';

-- Insert Office for Matterhorn Relocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Seestrasse 1', 'Rüschlikon', '8803', true
FROM relocators 
WHERE name ILIKE 'Matterhorn Relocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update OZ Swiss Relocation Consulting
UPDATE relocators 
SET 
    contact_email = 'info@oz-swiss.ch',
    phone_number = '+41 44 364 00 04',
    website = 'https://oz-swiss.ch/',
    founded_year = 1998,
    employee_count = 'Not specified',
    address_street = 'Im Grund 21',
    address_city = 'Embrach',
    address_zip = '8424'
WHERE name ILIKE 'OZ Swiss Relocation Consulting';

-- Insert Office for OZ Swiss Relocation Consulting
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Im Grund 21', 'Embrach', '8424', true
FROM relocators 
WHERE name ILIKE 'OZ Swiss Relocation Consulting'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Packimpex
UPDATE relocators 
SET 
    contact_email = 'info@packimpex.com',
    phone_number = '+41 58 356 14 14',
    website = 'https://www.packimpex.com/ch-en/home',
    founded_year = 1977,
    employee_count = 'Not specified',
    address_street = 'Brunnmattstrasse 5',
    address_city = 'Thörishaus, Bern',
    address_zip = '3174'
WHERE name ILIKE 'Packimpex';

-- Insert Office for Packimpex
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Brunnmattstrasse 5', 'Thörishaus, Bern', '3174', true
FROM relocators 
WHERE name ILIKE 'Packimpex'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Prime Relocation
UPDATE relocators 
SET 
    contact_email = 'info@primerelocation.ch',
    phone_number = '+41 41 760 74 41',
    website = 'https://www.primerelocation.ch/',
    founded_year = 2014,
    employee_count = 'Not specified',
    address_street = 'Industriestrasse 47',
    address_city = 'Zug',
    address_zip = '6300'
WHERE name ILIKE 'Prime Relocation';

-- Insert Office for Prime Relocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Industriestrasse 47', 'Zug', '6300', true
FROM relocators 
WHERE name ILIKE 'Prime Relocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Regio Basel WS Relocation
UPDATE relocators 
SET 
    contact_email = 'info@regiobaselwsrelocation.ch',
    phone_number = '+41 79 311 94 18',
    website = 'https://bsws.ch/',
    founded_year = NULL,
    employee_count = 'Not specified',
    address_street = 'Moosackerweg 24',
    address_city = 'Pfeffingen',
    address_zip = '4148'
WHERE name ILIKE 'Regio Basel WS Relocation';

-- Insert Office for Regio Basel WS Relocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Moosackerweg 24', 'Pfeffingen', '4148', true
FROM relocators 
WHERE name ILIKE 'Regio Basel WS Relocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Rel-Ex
UPDATE relocators 
SET 
    contact_email = 'welcome@rel-ex.ch',
    phone_number = '+41 79 858 04 77',
    website = 'https://rel-ex.ch/',
    founded_year = 2022,
    employee_count = '6',
    address_street = 'Rel-Ex Office',
    address_city = 'Zug',
    address_zip = '0000'
WHERE name ILIKE 'Rel-Ex';

-- Insert Office for Rel-Ex
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Rel-Ex Office', 'Zug', '0000', true
FROM relocators 
WHERE name ILIKE 'Rel-Ex'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Relocality
UPDATE relocators 
SET 
    contact_email = 'info@relocality.ch',
    phone_number = '+41 79 566 89 22',
    website = 'https://www.relocality.ch/',
    founded_year = 2010,
    employee_count = '5',
    address_street = 'Lange Gasse 43',
    address_city = 'Basel',
    address_zip = '4052'
WHERE name ILIKE 'Relocality';

-- Insert Office for Relocality
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Lange Gasse 43', 'Basel', '4052', true
FROM relocators 
WHERE name ILIKE 'Relocality'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Relocation Basel (h.o.m.e.s. GmbH)
UPDATE relocators 
SET 
    contact_email = 'info@homesbasel.com',
    phone_number = '+41-79-454-13-09',
    website = 'https://relocation-basel.ch/',
    founded_year = 1996,
    employee_count = 'Not Provided',
    address_street = 'Spechtweg 7',
    address_city = 'Riehen',
    address_zip = '4125'
WHERE name ILIKE 'Relocation Basel (h.o.m.e.s. GmbH)';

-- Insert Office for Relocation Basel (h.o.m.e.s. GmbH)
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Spechtweg 7', 'Riehen', '4125', true
FROM relocators 
WHERE name ILIKE 'Relocation Basel (h.o.m.e.s. GmbH)'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update RG Relocation Genevoise
UPDATE relocators 
SET 
    contact_email = 'contact@relocation-genevoise.ch',
    phone_number = '+41 22 715 17 48',
    website = 'https://relocation-genevoise.ch/en',
    founded_year = NULL,
    employee_count = 'Not specified',
    address_street = 'Rue des Alpes 5',
    address_city = 'Geneva',
    address_zip = '1201'
WHERE name ILIKE 'RG Relocation Genevoise';

-- Insert Office for RG Relocation Genevoise
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Rue des Alpes 5', 'Geneva', '1201', true
FROM relocators 
WHERE name ILIKE 'RG Relocation Genevoise'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Relocation Plus Switzerland
UPDATE relocators 
SET 
    contact_email = 'nschenkelaars@relocationplus.ch',
    phone_number = '+41 79 827 73 88',
    website = 'https://relocationplus.ch/',
    founded_year = 2010,
    employee_count = 'Not specified',
    address_street = 'Im Eichli 21',
    address_city = 'Oberägeri',
    address_zip = '6315'
WHERE name ILIKE 'Relocation Plus Switzerland';

-- Insert Office for Relocation Plus Switzerland
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Im Eichli 21', 'Oberägeri', '6315', true
FROM relocators 
WHERE name ILIKE 'Relocation Plus Switzerland'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Relocation Service (Cornelia Masciali)
UPDATE relocators 
SET 
    contact_email = 'masciali@yourrelocation.ch',
    phone_number = '+41 79 365 64 50',
    website = 'https://www.yourrelocation.ch/',
    founded_year = 2004,
    employee_count = 'Not specified',
    address_street = 'Relocation Service (Cornelia Masciali) Office',
    address_city = 'St. Gallen',
    address_zip = '9011'
WHERE name ILIKE 'Relocation Service (Cornelia Masciali)';

-- Insert Office for Relocation Service (Cornelia Masciali)
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Relocation Service (Cornelia Masciali) Office', 'St. Gallen', '9011', true
FROM relocators 
WHERE name ILIKE 'Relocation Service (Cornelia Masciali)'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update ReloNest
UPDATE relocators 
SET 
    contact_email = 'contact@relonest.com',
    phone_number = '+41 76 339 66 89',
    website = 'https://www.relonest.com/',
    founded_year = 2023,
    employee_count = '5',
    address_street = 'ReloNest Office',
    address_city = 'Zurich',
    address_zip = '0000'
WHERE name ILIKE 'ReloNest';

-- Insert Office for ReloNest
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'ReloNest Office', 'Zurich', '0000', true
FROM relocators 
WHERE name ILIKE 'ReloNest'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Santa Fe Relocation Services
UPDATE relocators 
SET 
    contact_email = 'geneva@santaferelo.com',
    phone_number = '+41 22 562 41 53',
    website = 'https://www.santaferelo.com/',
    founded_year = 1968,
    employee_count = 'Not specified',
    address_street = 'Route de Pré-Bois 20',
    address_city = 'Genève 15 Aéroport',
    address_zip = '1215'
WHERE name ILIKE 'Santa Fe Relocation Services';

-- Insert Office for Santa Fe Relocation Services
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Route de Pré-Bois 20', 'Genève 15 Aéroport', '1215', true
FROM relocators 
WHERE name ILIKE 'Santa Fe Relocation Services'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Schmid & Hoppler Relocation Services
UPDATE relocators 
SET 
    contact_email = 'info@schmid&hopplerrelocationservices.ch',
    phone_number = NULL,
    website = 'https://www.schmidhoppler-relocation.ch/',
    founded_year = NULL,
    employee_count = 'Not specified',
    address_street = 'Schmid & Hoppler Relocation Services Office',
    address_city = 'Wollerau/Freienbach',
    address_zip = '0000'
WHERE name ILIKE 'Schmid & Hoppler Relocation Services';

-- Insert Office for Schmid & Hoppler Relocation Services
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Schmid & Hoppler Relocation Services Office', 'Wollerau/Freienbach', '0000', true
FROM relocators 
WHERE name ILIKE 'Schmid & Hoppler Relocation Services'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Sgier + Partner
UPDATE relocators 
SET 
    contact_email = 'info@sgierpartner.ch',
    phone_number = '+41 44 123 45 67',
    website = 'https://sgierpartner.ch/',
    founded_year = 2001,
    employee_count = 'Not specified',
    address_street = 'Sgier + Partner Office',
    address_city = 'Zurich',
    address_zip = '0000'
WHERE name ILIKE 'Sgier + Partner';

-- Insert Office for Sgier + Partner
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Sgier + Partner Office', 'Zurich', '0000', true
FROM relocators 
WHERE name ILIKE 'Sgier + Partner'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Silver Nest Relocation Switzerland
UPDATE relocators 
SET 
    contact_email = 'office@silvernest.ch',
    phone_number = '+41 76 569 62 14',
    website = 'https://www.silvernest.ch/',
    founded_year = 2011,
    employee_count = 'Not specified',
    address_street = 'Gemeindestrasse 27',
    address_city = 'Zürich',
    address_zip = '8032'
WHERE name ILIKE 'Silver Nest Relocation Switzerland';

-- Insert Office for Silver Nest Relocation Switzerland
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Gemeindestrasse 27', 'Zürich', '8032', true
FROM relocators 
WHERE name ILIKE 'Silver Nest Relocation Switzerland'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Silverline Relocations
UPDATE relocators 
SET 
    contact_email = 'info@silverline-relocations.com',
    phone_number = '+41 78 631 71 10',
    website = 'https://www.silverline-relocations.com/',
    founded_year = 2005,
    employee_count = 'Not specified',
    address_street = 'Rue Eugène-Marziano 15',
    address_city = 'Les Acacias, Genève',
    address_zip = '1227'
WHERE name ILIKE 'Silverline Relocations';

-- Insert Office for Silverline Relocations
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Rue Eugène-Marziano 15', 'Les Acacias, Genève', '1227', true
FROM relocators 
WHERE name ILIKE 'Silverline Relocations'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Sirva Relocation
UPDATE relocators 
SET 
    contact_email = 'concierge@sirva.com',
    phone_number = '+12604292511',
    website = 'https://www.sirva.com/',
    founded_year = 2003,
    employee_count = '2900 (global)',
    address_street = 'Avenue des Morgines 12',
    address_city = 'Petit-Lancy',
    address_zip = '1213'
WHERE name ILIKE 'Sirva Relocation';

-- Insert Office for Sirva Relocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Avenue des Morgines 12', 'Petit-Lancy', '1213', true
FROM relocators 
WHERE name ILIKE 'Sirva Relocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update SRS - Solid Relocation and Sales
UPDATE relocators 
SET 
    contact_email = 'contact@srs-relocation.com',
    phone_number = '+41 76 364 76 32',
    website = 'https://srs-relocation.ch/',
    founded_year = 2013,
    employee_count = 'Not specified',
    address_street = '125, route de Lully',
    address_city = 'Bernex',
    address_zip = '1233'
WHERE name ILIKE 'SRS - Solid Relocation and Sales';

-- Insert Office for SRS - Solid Relocation and Sales
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, '125, route de Lully', 'Bernex', '1233', true
FROM relocators 
WHERE name ILIKE 'SRS - Solid Relocation and Sales'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Swiss Advisory Services
UPDATE relocators 
SET 
    contact_email = 'contact@swissadvisoryservices.com',
    phone_number = '+41 78 250 33 76',
    website = 'https://www.swissadvisoryservices.com/',
    founded_year = 2013,
    employee_count = 'Not specified',
    address_street = 'Swiss Advisory Services Office',
    address_city = 'Zurich-Oberrieden',
    address_zip = '0000'
WHERE name ILIKE 'Swiss Advisory Services';

-- Insert Office for Swiss Advisory Services
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Swiss Advisory Services Office', 'Zurich-Oberrieden', '0000', true
FROM relocators 
WHERE name ILIKE 'Swiss Advisory Services'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Swiss Expat Realtor
UPDATE relocators 
SET 
    contact_email = 'info@swissexpatrealtor.com',
    phone_number = '+41-79-577-06-97',
    website = 'https://www.swissexpatrealtor.com/',
    founded_year = 2018,
    employee_count = 'Not specified',
    address_street = 'Seestrasse 194',
    address_city = 'Wädenswil',
    address_zip = '8820'
WHERE name ILIKE 'Swiss Expat Realtor';

-- Insert Office for Swiss Expat Realtor
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Seestrasse 194', 'Wädenswil', '8820', true
FROM relocators 
WHERE name ILIKE 'Swiss Expat Realtor'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Swiss Prime International
UPDATE relocators 
SET 
    contact_email = 'info@swiss-prime.ch',
    phone_number = '+41 41 544 94 50',
    website = 'https://swiss-prime.ch/',
    founded_year = 2005,
    employee_count = 'Not specified',
    address_street = 'Swiss Prime International Office',
    address_city = 'Zug',
    address_zip = '0000'
WHERE name ILIKE 'Swiss Prime International';

-- Insert Office for Swiss Prime International
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Swiss Prime International Office', 'Zug', '0000', true
FROM relocators 
WHERE name ILIKE 'Swiss Prime International'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Swiss Relocation Services (All-in-One)
UPDATE relocators 
SET 
    contact_email = 'jennifer@swiss-relocation.ch',
    phone_number = '+41 79 465 48 55',
    website = 'https://swiss-relocation.ch/',
    founded_year = 2005,
    employee_count = '3',
    address_street = 'Swiss Relocation Services (All-in-One) Office',
    address_city = 'Regensdorf',
    address_zip = '0000'
WHERE name ILIKE 'Swiss Relocation Services (All-in-One)';

-- Insert Office for Swiss Relocation Services (All-in-One)
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Swiss Relocation Services (All-in-One) Office', 'Regensdorf', '0000', true
FROM relocators 
WHERE name ILIKE 'Swiss Relocation Services (All-in-One)'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update The Relocation Company & Consulting
UPDATE relocators 
SET 
    contact_email = 'n.elbel@the-relocation-company.ch',
    phone_number = '+41 79 833 22 52',
    website = 'https://the-relocation-company.ch/?lang=en',
    founded_year = 2010,
    employee_count = 'Not specified',
    address_street = 'Poststrasse 14',
    address_city = 'Zug',
    address_zip = '6300'
WHERE name ILIKE 'The Relocation Company & Consulting';

-- Insert Office for The Relocation Company & Consulting
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Poststrasse 14', 'Zug', '6300', true
FROM relocators 
WHERE name ILIKE 'The Relocation Company & Consulting'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Welcome Service
UPDATE relocators 
SET 
    contact_email = 'geneve@welcome-service.ch',
    phone_number = '+41 22 707 61 50',
    website = 'https://www.welcome-service.ch/',
    founded_year = 1990,
    employee_count = 'Not specified',
    address_street = 'Rue Zurlinden 6',
    address_city = 'Geneva',
    address_zip = '1207'
WHERE name ILIKE 'Welcome Service';

-- Insert Office for Welcome Service
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Rue Zurlinden 6', 'Geneva', '1207', true
FROM relocators 
WHERE name ILIKE 'Welcome Service'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Zug Relocation
UPDATE relocators 
SET 
    contact_email = 'welcome@zug-relocation.ch',
    phone_number = 'Not Provided # TODO: Add phone if available',
    website = 'https://www.zug-relocation.ch/',
    founded_year = 2010,
    employee_count = 'Not specified',
    address_street = 'Sumpfstrasse 32',
    address_city = 'Steinhausen',
    address_zip = '6312'
WHERE name ILIKE 'Zug Relocation';

-- Insert Office for Zug Relocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Sumpfstrasse 32', 'Steinhausen', '6312', true
FROM relocators 
WHERE name ILIKE 'Zug Relocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Zurich Relocation
UPDATE relocators 
SET 
    contact_email = 'info@zurichrelocation.ch',
    phone_number = NULL,
    website = 'https://zurichrelocation.ch',
    founded_year = NULL,
    employee_count = 'Not specified',
    address_street = 'Zurich Relocation Office',
    address_city = 'Zurich',
    address_zip = '0000'
WHERE name ILIKE 'Zurich Relocation';

-- Insert Office for Zurich Relocation
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Zurich Relocation Office', 'Zurich', '0000', true
FROM relocators 
WHERE name ILIKE 'Zurich Relocation'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);

-- Update Zweers include GmbH
UPDATE relocators 
SET 
    contact_email = 'info@zweers-include.com',
    phone_number = '+41-77-454-54-64',
    website = 'https://www.zweers-include.com/',
    founded_year = 2023,
    employee_count = '"Not Provided" # TODO: Add number of employees if available',
    address_street = 'Not Provided # TODO: Add street address if available',
    address_city = 'Basel',
    address_zip = 'Not Provided'
WHERE name ILIKE 'Zweers include GmbH';

-- Insert Office for Zweers include GmbH
INSERT INTO relocator_offices (relocator_id, street, city, zip, is_main)
SELECT id, 'Not Provided # TODO: Add street address if available', 'Basel', 'Not Provided', true
FROM relocators 
WHERE name ILIKE 'Zweers include GmbH'
AND NOT EXISTS (
    SELECT 1 FROM relocator_offices WHERE relocator_id = relocators.id AND is_main = true
);
