[build]
  command = "npm run build"
  publish = "dist"

# Environment variable configuration
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Handle 404s for static site
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 