[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  CI = "true"
  NODE_OPTIONS = "--max_old_space_size=4096"

# Normalize legacy service URLs to consolidated slugs
[[redirects]]
  from = "/services/visa-immigration"
  to = "/services/visa"
  status = 301
  force = true

[[redirects]]
  from = "/services/banking"
  to = "/services/banking-finance"
  status = 301
  force = true

[[redirects]]
  from = "/services/immigration-services"
  to = "/services/visa"
  status = 301
  force = true
