import { Resend } from 'resend';
import { createClient } from '@supabase/supabase-js';
import AgencyOpportunity from '../../../../emails/AgencyOpportunity';

export const prerender = false;

const resend = new Resend(process.env.RESEND_API_KEY);
const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST({ request }: { request: Request }) {
    try {
        const { leadId, partnerIds } = await request.json();

        if (!leadId || !partnerIds || !Array.isArray(partnerIds)) {
            return new Response(JSON.stringify({ error: 'Invalid request body' }), { status: 400 });
        }

        // 1. Fetch Lead Details
        const { data: lead, error: leadError } = await supabase
            .from('leads')
            .select('*')
            .eq('id', leadId)
            .single();

        if (leadError || !lead) {
            return new Response(JSON.stringify({ error: 'Lead not found' }), { status: 404 });
        }

        const results = [];

        // 2. Loop through partners to send emails
        for (const partnerId of partnerIds) {
            // a. Get or Create Quote to generate Token
            // Check if quote already exists
            const { data: existingQuote } = await supabase
                .from('quotes')
                .select('*')
                .eq('lead_id', leadId)
                .eq('agency_id', partnerId)
                .single();

            let token = existingQuote?.token;

            if (!existingQuote) {
                // Create new quote
                const { data: newQuote, error: createError } = await supabase
                    .from('quotes')
                    .insert({
                        lead_id: leadId,
                        agency_id: partnerId,
                        status: 'pending',
                        // Token is auto-generated by DB default if set, but let's generate one if not
                        // Assuming DB has default uuid_generate_v4() or similar for ID. 
                        // For token, let's generate a random string if DB doesn't handle it.
                        // But let's assume we rely on the `token` column. 
                        // Better to generate it here to be safe and use it immediately.
                        token: crypto.randomUUID(),
                    })
                    .select()
                    .single();

                if (createError) {
                    console.error(`Failed to create quote for agency ${partnerId}`, createError);
                    results.push({ partnerId, status: 'failed_db', error: createError.message });
                    continue;
                }
                token = newQuote.token;
            }

            // b. Fetch Partner Email
            const { data: partner } = await supabase
                .from('relocators')
                .select('contact_email, internal_email, manager_email')
                .eq('id', partnerId)
                .single();

            if (!partner) {
                results.push({ partnerId, status: 'failed_partner_not_found' });
                continue;
            }

            // c. Send Email
            // Prioritize: Manager Email -> Contact Email -> Internal Email -> Default
            const recipientEmail = partner.manager_email || partner.contact_email || partner.internal_email;

            if (!recipientEmail) {
                results.push({ partnerId, status: 'failed_no_email' });
                continue;
            }

            const quoteLink = `${process.env.NEXT_PUBLIC_BASE_URL}/agency/quote?token=${token}`;

            const { data: emailData, error: emailError } = await resend.emails.send({
                from: 'ReloFinder Partner <partners@relofinder.ch>',
                to: [recipientEmail],
                subject: `New Opportunity: Relocation to ${lead.destination_canton}`,
                react: AgencyOpportunity({
                    leadSummary: {
                        origin: lead.origin_country || 'International',
                        destination: lead.destination_canton || 'Switzerland',
                        familySize: `${lead.family_size || 1} Person(s)`, // Simple fallback
                        moveDate: lead.move_date ? new Date(lead.move_date).toLocaleDateString() : 'Flexible',
                    },
                    quoteLink: quoteLink,
                }) as any,
            }) as any;

            if (emailError) {
                console.error(`Failed to send email to ${recipientEmail}`, emailError);
                results.push({ partnerId, status: 'failed_resend', error: emailError });
            } else {
                results.push({ partnerId, status: 'sent', emailId: emailData?.id });
            }
        }

        return new Response(JSON.stringify({ success: true, results }), {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
        });

    } catch (error: any) {
        console.error('Distribute Lead Error:', error);
        return new Response(JSON.stringify({ error: error.message }), { status: 500 });
    }
}
